import type { NextPage } from 'next'
import Skeleton from '@mui/material/Skeleton'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className="fixed inset-0 flex">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col items-center m-auto">
        <p className="text-2xl mb-4">This circle skeleton will be perfect circle on development, but squished on production.</p>

        <Skeleton className="w-20 h-20" variant="circular" />
      </div>
    </div>
  )
}

export default Home
